version: '3.8'
services:
  php-apache-server:
    container_name: php-apache-server
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "7110:80"
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: tutorials
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "8010:3306"
  admin:
    container_name: admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

